### ISSUE TITLE
Which tool did you use to create the timeline view of the performance of the PHP scripts?

### ISSUE THREAD

**Issue by jaspersmitNL** [realFlowControl/1brc#3]
Which tool did you use to create the timeline view of the performance of the PHP scripts?

**Comment by maastrixbackup** [comment]
njkhjkhjk

**Comment by realFlowControl** [comment]
Hey there 👋 
in my day job I am working on the continuous PHP profiler for Datadog in this repository: https://github.com/DataDog/dd-trace-php
And this is the profiler I used to gather performance data and this is also where the screenshots are taken from.
